[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = false
  minify = false
[build.processing.js]
  bundle = false
  minify = false
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = false

[[redirects]]
  from = "/*"
  to = "error/404.html"
  status = 404

# Project page redirects.
[[redirects]]
  from = "/project1"
  to = "/project/pro1"
  status = 200
  force = true

[[redirects]]
  from = "/projekt1"
  to = "/project/pro1"
  status = 200
  force = true

[[redirects]]
  from = "/project1"
  to = "/project/pro1"
  status = 200
  force = true

[[redirects]]
  from = "/projekt2"
  to = "/project/pro2"
  status = 200
  force = true

[[redirects]]
  from = "/project3"
  to = "/project/pro3"
  status = 200
  force = true

[[redirects]]
  from = "/projekt3"
  to = "/project/pro3"
  status = 200
  force = true